### [CVE-2025-4516](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4516)
![](https://img.shields.io/static/v1?label=Product&message=CPython&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=0%20&color=brightgreen)
![](https://img.shields.io/static/v1?label=Version&message=3.10.0%20&color=brightgreen)
![](https://img.shields.io/static/v1?label=Version&message=3.11.0%20&color=brightgreen)
![](https://img.shields.io/static/v1?label=Version&message=3.12.0%20&color=brightgreen)
![](https://img.shields.io/static/v1?label=Version&message=3.13.0%20&color=brightgreen)
![](https://img.shields.io/static/v1?label=Version&message=3.14.0a1%20&color=brightgreen)
![](https://img.shields.io/static/v1?label=Vulnerability&message=CWE-416%20Use%20After%20Free&color=brightgreen)

### Description

There is an issue in CPython when using `bytes.decode("unicode_escape", error="ignore|replace")`. If you are not using the "unicode_escape" encoding or an error handler your usage is not affected. To work-around this issue you may stop using the error= handler and instead wrap the bytes.decode() call in a try-except catching the DecodeError.

### POC

#### Reference
No PoCs from references.

#### Github
- https://github.com/CKA-codespace/cg-compare
- https://github.com/GitHubForSnap/matrix-commander-gael
- https://github.com/adegoodyer/kubernetes-admin-toolkit

