### [CVE-2023-29824](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-29824)
![](https://img.shields.io/static/v1?label=Product&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Vulnerability&message=n%2Fa&color=brighgreen)

### Description

** DISPUTED ** A use-after-free issue was discovered in Py_FindObjects() function in SciPy versions prior to 1.8.0. NOTE: the vendor and discoverer indicate that this is not a security issue.

### POC

#### Reference
- https://github.com/scipy/scipy/issues/14713
- https://github.com/scipy/scipy/issues/14713#issuecomment-1629468565

#### Github
- https://github.com/vin01/bogus-cves

