### [CVE-2009-5011](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2009-5011)
![](https://img.shields.io/static/v1?label=Product&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Vulnerability&message=n%2Fa&color=brighgreen)

### Description

Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.2 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the getpeername function having an ENOTCONN error, a different vulnerability than CVE-2010-3494.

### POC

#### Reference
- http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY

#### Github
No PoCs found on GitHub currently.

