### [CVE-2019-14234](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-14234)
![](https://img.shields.io/static/v1?label=Product&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Vulnerability&message=n%2Fa&color=brighgreen)

### Description

An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. Due to an error in shallow key transformation, key and index lookups for django.contrib.postgres.fields.JSONField, and key lookups for django.contrib.postgres.fields.HStoreField, were subject to SQL injection. This could, for example, be exploited via crafted use of "OR 1=1" in a key or index name to return all records, using a suitably crafted dictionary, with dictionary expansion, as the **kwargs passed to the QuerySet.filter() function.

### POC

#### Reference
No PoCs from references.

#### Github
- https://github.com/ARPSyndicate/cvemon
- https://github.com/CLincat/vulcat
- https://github.com/Rivaill/CVE_2019_14234
- https://github.com/SexyBeast233/SecBooks
- https://github.com/SurfRid3r/Django_vulnerability_analysis
- https://github.com/Threekiii/Awesome-POC
- https://github.com/Threekiii/Vulhub-Reproduce
- https://github.com/TrojanAZhen/Self_Back
- https://github.com/bakery312/Vulhub-Reproduce
- https://github.com/hktalent/bug-bounty
- https://github.com/hxysaury/saury-vulnhub
- https://github.com/kvesta/vesta
- https://github.com/lnick2023/nicenice
- https://github.com/malvika-thakur/CVE-2019-14234
- https://github.com/q99266/saury-vulnhub
- https://github.com/qazbnm456/awesome-cve-poc
- https://github.com/reph0r/Poc-Exp-Tools
- https://github.com/reph0r/Shooting-Range
- https://github.com/reph0r/poc-exp
- https://github.com/reph0r/poc-exp-tools
- https://github.com/t0m4too/t0m4to
- https://github.com/xbl3/awesome-cve-poc_qazbnm456
- https://github.com/yihong0618/Python365

