### [CVE-2020-15701](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15701)
![](https://img.shields.io/static/v1?label=Product&message=apport&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=2.20.1%3C%202.20.1-0ubuntu2.24%20&color=brighgreen)
![](https://img.shields.io/static/v1?label=Vulnerability&message=CWE-755%20Improper%20Handling%20of%20Exceptional%20Conditions&color=brighgreen)

### Description

An unhandled exception in check_ignored() in apport/report.py can be exploited by a local attacker to cause a denial of service. If the mtime attribute is a string value in apport-ignore.xml, it will trigger an unhandled exception, resulting in a crash. Fixed in 2.20.1-0ubuntu2.24, 2.20.9-0ubuntu7.16, 2.20.11-0ubuntu27.6.

### POC

#### Reference
No PoCs from references.

#### Github
- https://github.com/Live-Hack-CVE/CVE-2020-15701

