### [CVE-2022-35969](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-35969)
![](https://img.shields.io/static/v1?label=Product&message=tensorflow&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=%3C%202.7.2%20&color=brightgreen)
![](https://img.shields.io/static/v1?label=Version&message=%3E%3D%202.8.0%2C%20%3C%202.8.1%20&color=brightgreen)
![](https://img.shields.io/static/v1?label=Version&message=%3E%3D%202.9.0%2C%20%3C%202.9.1%20&color=brightgreen)
![](https://img.shields.io/static/v1?label=Vulnerability&message=CWE-617%3A%20Reachable%20Assertion&color=brightgreen)

### Description

TensorFlow is an open source platform for machine learning. The implementation of `Conv2DBackpropInput` requires `input_sizes` to be 4-dimensional. Otherwise, it gives a `CHECK` failure which can be used to trigger a denial of service attack. We have patched the issue in GitHub commit 50156d547b9a1da0144d7babe665cf690305b33c. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue.

### POC

#### Reference
No PoCs from references.

#### Github
- https://github.com/gclonly/im

