### [CVE-2021-25288](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-25288)
![](https://img.shields.io/static/v1?label=Product&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Vulnerability&message=n%2Fa&color=brighgreen)

### Description

An issue was discovered in Pillow before 8.2.0. There is an out-of-bounds read in J2kDecode, in j2ku_gray_i.

### POC

#### Reference
- https://github.com/python-pillow/Pillow/pull/5377#issuecomment-833821470

#### Github
No PoCs found on GitHub currently.

